### ISSUE TITLE
Research - Micro Frontends

### ISSUE THREAD

**Issue by bellanov** [bellanov/andy#2]
Summarize Micro Frontends and their applications.

**References:**
> Micro Frontends - https://micro-frontends.org/
> GitHub Repository - https://github.com/teabyii/tractor-store-react

**Tasks:**
- Read and summarize the content within the above _URL_
- Submit findings as a Markdown document within the _DESIGN_PATTERNS_ directory

**Comment by bellanov** [comment]
Start with the base layout (Header, Main, Footer) then extrapolate to Micro Frontends as more complex components are added to UIs. 

No massive component library, other than a base. Webpack Module federation is something to look into.

**Comment by aybanda** [comment]
@bellanov 
check out #24 
review and let me know what I'm lacking.

**Comment by bellanov** [comment]
Not lacking anything. Just don't do issues not assigned to you lol.

Moving the etl-pipeline forward a bit then I'll have some for you. It's far from complete.

**Comment by aybanda** [comment]
my bad, assumed you were asking for help to complete 
will not intervene further

**Comment by bellanov** [comment]
NP. Should have something for you shortly.

Once I move the pipeline forward a bit, I have real data and a real use case for you to code to.

Curious what you come up with.
