### ISSUE TITLE
Architecture & Billing Summary

### ISSUE THREAD

**Issue by bellanov** [bellanov/andy#33]
Summarize the current architecture and any relevant costs, spanning **GCP**, **Docker**, and **GitHub**.

## Operational Costs : $55 / month

**Google Cloud Platform** 

_$46 / month_ 
Google Workspace Enterprise Plus: Usage of 2 seats

- Administrator Account
- Development Account
 
**Docker**

_$5 / month_
Artifact registry for Docker containers.

**GitHub**

_$4 / month_
Source code repository. CICD Builds.

_$0 / month_ 
Google Projects

- Alexei
- Andy
- Bellanov
- FantasyAce
- Puter

**Amazon Web Services** 

_$0 / month_ 
Deployment of AWS resources.

**HashiCorp Terraform Registry**

_$0 / month_
Public registry to host Terraform Modules.

**PyPi Python Package Index**

_$0 / month_
Public registry to host Python packages.

**Comment by bellanov** [comment]
Need to confirm and get all projects in sync, with regards to modules.

This means creating open source Terraform repositories and migrating the code to using those modules directly.

**Comment by bellanov** [comment]
@aybanda @prattsvee just review the above as it our stack thus far.

Need to bee line towards K8s while establishing the data science artifacts to deploy.

**Comment by aybanda** [comment]
@bellanov 
Got it, thanks for the heads up on our stack and where we're headed. I've taken a look at what you've shared.
Sounds like we're gearing up for K8s and prepping our data science stuff for deployment. 
 will circle back if anything comes to mind or if we need to hash out any details.
Appreciate you keeping us in the loop!

**Comment by aybanda** [comment]
> Need to confirm and get all projects in sync, with regards to modules.
> 
> This means creating open source Terraform repositories and migrating the code to using those modules directly.

sounds like a solid plan,
this should help streamline things and make our setup more consistent across the board. It'll probably save us some headaches down the line too.

**Comment by prattsvee** [comment]
I think we can move to k8s I can take up K8's and write Helm to maintain those pods.

**Comment by bellanov** [comment]
Sounds good. The mission is the same on both ends.

You on the AWS side, me on GCP.

A few more issues for you both incoming.
